### ISSUE TITLE
Extended status about the robot

### ISSUE THREAD

**Issue by simonschmeisser** [kroshu/kuka-external-control-sdk#11]
Is there a way to get information about the current robot status?

- T1/T2/Automatic
- drives powered
- E-Stop

and more advanced:

- payload
- joint limits (are there actually soft limits?)
- model name

**Comment by VX792** [comment]
Hello!

Sadly it's not currently possible to retrieve any of these data through the client library. Theoretically it could be possible to forward these to the user, but I don't think this will be supported anytime in the future, at least for the iisy robots.

**Comment by simonschmeisser** [comment]
So I need to either write a capability and forward it somehow and/or try to see what I can map to Profinet?

**Comment by Svastits** [comment]
Yes, I think these two are the only options
